# Generated by Django 5.0 on 2025-06-16 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisresult',
            old_name='detailed_feedback',
            new_name='raw_analysis',
        ),
    ]
