# Generated by Django 5.0 on 2025-06-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_rename_detailed_feedback_analysisresult_raw_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
